-- Seed exercises generated from exercise_library_60.json
begin;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'bodyweight-squat',
      'Bodyweight Squat',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{2,3}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'box-squat',
      'Box Squat',
      'mobility',
      'mobility',
      '{step}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{1,3}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'wall-sit',
      'Wall Sit',
      'mobility',
      'mobility',
      '{wall}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{1,2}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'glute-bridge',
      'Glute Bridge',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{5,6}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'single-leg-glute-bridge',
      'Single-Leg Glute Bridge',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{4,6}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'clamshell',
      'Clamshell',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{4,5}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'reverse-lunge',
      'Reverse Lunge',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{8,9}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'split-squat',
      'Split Squat',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{7,9}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'step-up',
      'Step-Up',
      'mobility',
      'mobility',
      '{step}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{7,8}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'calf-raise',
      'Calf Raise',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      false,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{11,12}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'single-leg-calf-raise',
      'Single-Leg Calf Raise',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      false,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{10,12}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'lateral-walk-with-band',
      'Lateral Walk with Band',
      'mobility',
      'mobility',
      '{band}'::text[],
      'beginner',
      false,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{6,4}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'plank',
      'Plank',
      'core',
      'conditioning',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{14,15}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'modified-plank-knees',
      'Modified Plank (Knees)',
      'core',
      'conditioning',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{13,15}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'dead-bug',
      'Dead Bug',
      'core',
      'conditioning',
      '{bodyweight}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{13,14}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'bird-dog',
      'Bird Dog',
      'core',
      'conditioning',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{15,17}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'side-plank',
      'Side Plank',
      'core',
      'conditioning',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{18,16}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'modified-side-plank-knees',
      'Modified Side Plank (Knees)',
      'core',
      'conditioning',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{17,16}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'pallof-press',
      'Pallof Press',
      'core',
      'conditioning',
      '{band}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{16,15}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'hollow-body-hold',
      'Hollow Body Hold',
      'core',
      'conditioning',
      '{bodyweight}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{15,21}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'bicycle-crunch',
      'Bicycle Crunch',
      'core',
      'conditioning',
      '{bodyweight}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{20,15}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'push-up',
      'Push-Up',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{23,24}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'modified-push-up-knees',
      'Modified Push-Up (Knees)',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{22,24}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'wall-push-up',
      'Wall Push-Up',
      'mobility',
      'mobility',
      '{wall}'::text[],
      'beginner',
      true,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{22,23}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'incline-push-up',
      'Incline Push-Up',
      'mobility',
      'mobility',
      '{bench}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{23,24}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'dumbbell-row',
      'Dumbbell Row',
      'mobility',
      'mobility',
      '{db}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{27,28}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'inverted-row',
      'Inverted Row',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{26,28}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'bent-over-row',
      'Bent-Over Row',
      'mobility',
      'mobility',
      '{db}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{26,27}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'lat-pulldown',
      'Lat Pulldown',
      'mobility',
      'mobility',
      '{band}'::text[],
      'beginner',
      false,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{27,26}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'shoulder-press',
      'Shoulder Press',
      'mobility',
      'mobility',
      '{db}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{31,32}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'lateral-raise',
      'Lateral Raise',
      'mobility',
      'mobility',
      '{db}'::text[],
      'beginner',
      false,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{30,32}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'front-raise',
      'Front Raise',
      'mobility',
      'mobility',
      '{db}'::text[],
      'beginner',
      false,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{30,31}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'bicep-curl',
      'Bicep Curl',
      'mobility',
      'mobility',
      '{db}'::text[],
      'beginner',
      false,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{34,35}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'hammer-curl',
      'Hammer Curl',
      'mobility',
      'mobility',
      '{db}'::text[],
      'beginner',
      false,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{33,35}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'resistance-band-curl',
      'Resistance Band Curl',
      'mobility',
      'mobility',
      '{band}'::text[],
      'beginner',
      false,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{33,34}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'tricep-dip',
      'Tricep Dip',
      'mobility',
      'mobility',
      '{bench}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{37,38}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'overhead-tricep-extension',
      'Overhead Tricep Extension',
      'mobility',
      'mobility',
      '{db}'::text[],
      'beginner',
      false,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{36,38}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'tricep-kickback',
      'Tricep Kickback',
      'mobility',
      'mobility',
      '{db}'::text[],
      'beginner',
      false,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{36,37}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'chest-fly-dumbbell',
      'Chest Fly (Dumbbell)',
      'mobility',
      'mobility',
      '{db,bench}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{40,24}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'standing-chest-fly-band',
      'Standing Chest Fly (Band)',
      'mobility',
      'mobility',
      '{band}'::text[],
      'beginner',
      true,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{39,24}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'face-pull',
      'Face Pull',
      'mobility',
      'mobility',
      '{band}'::text[],
      'beginner',
      false,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{26,28}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'reverse-fly',
      'Reverse Fly',
      'mobility',
      'mobility',
      '{db}'::text[],
      'beginner',
      true,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{41,26}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'superman-hold',
      'Superman Hold',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{16,44}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'back-extension',
      'Back Extension',
      'mobility',
      'mobility',
      '{bench}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{43,16}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'good-morning',
      'Good Morning',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{46,4}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'romanian-deadlift',
      'Romanian Deadlift',
      'mobility',
      'mobility',
      '{db}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{45,4}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'jumping-jack',
      'Jumping Jack',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{48,49}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'step-out-jack',
      'Step-Out Jack',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{47,49}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'high-knees',
      'High Knees',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{50,48}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'marching-in-place',
      'Marching in Place',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      false,
      false,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{49,48}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'mountain-climber',
      'Mountain Climber',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{52,48}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'plank-shoulder-tap',
      'Plank Shoulder Tap',
      'core',
      'conditioning',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{51,14}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'burpee',
      'Burpee',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{54,48}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'squat-thrust',
      'Squat Thrust',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{53,48}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'inchworm',
      'Inchworm',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{56,45}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'walkout-to-plank',
      'Walkout to Plank',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{55,14}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'bear-crawl',
      'Bear Crawl',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      true,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{16,58}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'crab-walk',
      'Crab Walk',
      'mobility',
      'mobility',
      '{bodyweight}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{57,4}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'farmer-s-carry',
      'Farmer''s Carry',
      'mobility',
      'mobility',
      '{db}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{60,1}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
insert into public.exercises 
    (slug,name,pattern,goal,equipment,difficulty,binder_aware,pelvic_floor_safe,contraindications,
     cue_primary,cues,breathing,coaching_points,common_errors,progressions,regressions,swaps,
     rep_5min,rep_15min,rep_30min,rep_45min,version,last_reviewed_at,reviewer)
    values (
      'suitcase-carry',
      'Suitcase Carry',
      'mobility',
      'mobility',
      '{db}'::text[],
      'beginner',
      false,
      true,
      '{}'::text[],
      'Neutral ribs, long neck, easy breath.',
      '{Exhale as you work,Keep range comfortable,Ribs quiet}'::text[],
      'Exhale on exertion. Avoid breath holding.',
      '{Stable base,Controlled tempo,Comfortable range}'::text[],
      '{Shrugging,Rushing tempo,Overextending}'::text[],
      '{Add reps,Slow tempo 3-1-3,Pause at peak}'::text[],
      '{Reduce range,Use support,Decrease load/band tension}'::text[],
      '{59,1}'::text[],
      '2×30–60s or 2×8 @RPE 7',
      '3×8–12, rest 45s',
      '4×8–10, rest 60s + iso 2×30s',
      '5×6–10, rest 60–75s + finisher',
      '1.0.0',
      '2025-11-13',
      'TransFitness v1 Editorial'
    ) on conflict (slug) do nothing;
commit;