-- Analytics events table for beta funnel tracking.
--
-- Stores PRD §9 events from the mobile app. Receives writes from the app
-- via the anon key (so RLS allows INSERT but NOT SELECT/UPDATE/DELETE for
-- anon). Reads happen via service role from Supabase Studio or scripts.
--
-- Privacy notes:
-- - Never write sensitive health/profile data to this table. The mobile
--   client (src/services/analytics) only sends event_type, a non-sensitive
--   properties bag, anonymized user_id (Supabase auth UID), and timestamps.
-- - Per the PRD privacy stance, this table contains usage data only —
--   absolutely no body part references, no HRT details, no dysphoria scores,
--   no goal text, etc.
--
-- Run this in Supabase Studio → SQL Editor once, on the same project the
-- app already uses (EXPO_PUBLIC_SUPABASE_URL).

CREATE TABLE IF NOT EXISTS public.analytics_events (
    id BIGSERIAL PRIMARY KEY,
    -- Anonymous device id (Supabase auth user id if signed in, otherwise
    -- a stable per-install UUID generated by the app). Kept nullable so
    -- pre-auth events (e.g. signup_completed) can still land.
    user_id TEXT,
    event_type TEXT NOT NULL,
    properties JSONB DEFAULT '{}'::jsonb,
    -- Event time as recorded on-device. Separate from server_at so we can
    -- detect clock skew or batched uploads after offline use.
    occurred_at TIMESTAMPTZ NOT NULL,
    server_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Useful for breaking down by app version once we have one.
    app_version TEXT,
    platform TEXT
);

CREATE INDEX IF NOT EXISTS analytics_events_event_type_idx
    ON public.analytics_events (event_type);

CREATE INDEX IF NOT EXISTS analytics_events_user_id_idx
    ON public.analytics_events (user_id)
    WHERE user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS analytics_events_occurred_at_idx
    ON public.analytics_events (occurred_at DESC);

-- RLS: anon can insert, nobody can read/update/delete with anon key.
-- Service role (used in Supabase Studio + server scripts) bypasses RLS.
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "analytics_events_insert_anon" ON public.analytics_events;
CREATE POLICY "analytics_events_insert_anon"
    ON public.analytics_events
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

-- No SELECT policy intentionally — reads only via service role.
